name: Generator
on:
  - push
  - pull_request

jobs:
  generator:
    env:
      TS_MAX_DELTA: 3
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - run: bin/fetch-configlet
      - run: bin/configlet sync || true

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@9f8c263975569ff3b4e510cb1f8813115749e146

      - run: carton install
      - run: cpm install App::Yath

      - run: carton exec -- yath start

      - name: Test generator
        run: carton exec -- yath run t/generator

      - name: Generated files match generator output
        run: carton exec -- yath run t/files
