recommends 'Moo';       # https://perldoc.pl/Moo
suggests 'Mo';          # https://perldoc.pl/Mo
suggests 'Moose';       # https://perldoc.pl/Moose
suggests 'Object::Pad'; # https://perldoc.pl/Object::Pad
suggests 'Class::Tiny'; # https://perldoc.pl/Class::Tiny#Why-this-instead-of-Moose-or-Moo?
